export enum ErrorCode {
  EXISTED_ACCOUNT = 'EXISTED_ACCOUNT',
  PASSWORD_NOT_MATCHED = 'PASSWORD_NOT_MATCHED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_NOT_ALLOWED = 'FILE_NOT_ALLOWED',
  FILE_MAX_LENGTH_EXCEEDED = 'FILE_MAX_LENGTH_EXCEEDED',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
}
